name: ENE
favicon: null
layout_spectrum: 0.66115
typography_spectrum: 0.86826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.03733348334208131
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
